
[[Services]]
Name = "redis"
Image = "redis:7-alpine"
Port = 6379

[[Functions]]
Name = "greeter"
Method = "GET"
Type = "mux"

[[Functions]]
Name = "person.show"
Action = "show"
Method = "GET"
Type = "mux"
    [Functions.Model]
    Name = "Person"
        [[Functions.Model.Fields]]
        Name = "Name"
        Type = "string"
    [Functions.Redis]
    host = "redis"
    port = "6379"
    db = 0
    password = ""

[[Functions]]
Name = "person.store"
Action = "store"
Method = "POST"
Type = "mux"

    [Functions.Model]
    Name = "Person"
        [[Functions.Model.Fields]]
        Name = "Name"
        Type = "string"
    
    [Functions.Redis]
    host = "redis"
    port = "6379"
    db = 0
    password = ""

[[Functions]]
Name = "person.update"
Action = "update"
Method = "POST"
Type = "mux"

    [Functions.Model]
    Name = "Person"
        [[Functions.Model.Fields]]
        Name = "Name"
        Type = "string"
    
    [Functions.Redis]
    host = "redis"
    port = "6379"
    db = 0
    password = ""

[[Functions]]
Name = "person.destroy"
Action = "destroy"
Method = "POST"
Type = "mux"

    [Functions.Model]
    Name = "Person"
        [[Functions.Model.Fields]]
        Name = "Name"
        Type = "string"
    
    [Functions.Redis]
    host = "redis"
    port = "6379"
    db = 0
    password = ""

[[Functions]]
Name = "gateway"
Type = "gateway"