[[Functions]]
Name = "person.store"
Method = "POST"
Type = "mux"
ActionType = "store"
Redis = true

    [Functions.Model]
        [[Functions.Model.Fields]]
        Key = "name"
        Type = "string"
        [[Functions.Model.Fields]]
        Key = "age"
        Type = "int"

[[Functions]]
Name = "person.update"
Method = "POST"
Type = "mux"

[[Functions]]
Name = "person.destroy"
Method = "POST"
Type = "mux"

[[Functions]]
Name = "person.index"
Method = "GET"
Type = "mux"

[[Functions]]
Name = "person.show"
Method = "GET"
Type = "mux"

[[Functions]]
Name = "gateway"
Type = "gateway"